# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build and test'

    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '.'
        outputPath: '$(Pipeline.Workspace)/Package/'
        updateTasksVersion: false
        extensionPricing: 'free'
    - task: PublishAzureDevOpsExtension@2
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Marketplace'
              fileType: 'vsix'
              vsixFile: '**/PublishReleaseArtifactsExtension.vsix'
              updateTasksVersionType: 'patch'
              extensionVisibility: 'privatepreview'
              extensionPricing: 'free'
              shareWith: 'https://benjsawesometfstest.visualstudio.com'