# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TfxInstaller@2
      inputs:
        version: 'v0.6.x'
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        cd PublishReleaseArtifactTask
        npm install
        npm run build
        cd ../DownloadReleaseArtifactTask
        npm install
        npm run build
      displayName: 'npm install and build'
    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '.'
        outputPath: '$(Pipeline.Workspace)/Package/PublishReleaseArtifactsExtension.vsix'
        updateTasksVersion: true
        updateTasksVersionType: 'patch'
        extensionVisibility: 'public_preview'
        extensionPricing: 'free'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/Package'
        artifact: 'PublishReleaseArtifactsExtension'
        publishLocation: 'pipeline'